release: python manage.py runserver
web: daphne KAMassignment.wsgi:application --port $PORT --bind 0.0.0.0 -v2
celery: celery -A KAMassignment.celery worker --pool=solo -l info
celerybeat: celery -A KAMassignment beat -l info 