# Generated by Django 3.2.1 on 2024-12-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leads',
            fields=[
                ('leadID', models.BigAutoField(primary_key=True, serialize=False)),
                ('restaurantName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('currentStatus', models.CharField(max_length=10)),
                ('KAMID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tracking',
            fields=[
                ('trackingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('leadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KAM.leads')),
            ],
        ),
        migrations.CreateModel(
            name='interactionLogging',
            fields=[
                ('interactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=100)),
                ('followUp', models.CharField(max_length=10)),
                ('leadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KAM.leads')),
            ],
        ),
    ]
