# Generated by Django 4.2.17 on 2024-12-26 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leads',
            fields=[
                ('leadID', models.BigAutoField(primary_key=True, serialize=False)),
                ('restaurantName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(default='Kota', max_length=30)),
                ('state', models.CharField(default='Rajasthan', max_length=20)),
                ('country', models.CharField(default='India', max_length=20)),
                ('contactNumber', models.CharField(max_length=10)),
                ('currentStatus', models.CharField(max_length=10)),
                ('KAMID', models.CharField(max_length=10)),
                ('callFrequency', models.IntegerField(default=10)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('lastCallMade', models.DateField(default=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='tracking',
            fields=[
                ('trackingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('emailID', models.EmailField(max_length=254)),
                ('leadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KAM.leads')),
            ],
        ),
        migrations.CreateModel(
            name='interactionLogging',
            fields=[
                ('interactionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=100)),
                ('followUp', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('leadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KAM.leads')),
            ],
        ),
    ]
