# Generated by Django 3.2.1 on 2024-12-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionlogging',
            name='date',
        ),
    ]
