# Generated by Django 3.2.1 on 2024-12-23 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0002_remove_interactionlogging_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlogging',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
