# Generated by Django 3.2.1 on 2024-12-23 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0003_interactionlogging_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='emailID',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
