# Generated by Django 3.2.1 on 2024-12-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0004_tracking_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='emailID',
        ),
    ]
