# Generated by Django 3.2.1 on 2024-12-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0005_remove_tracking_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='emailID',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
