# Generated by Django 4.2.17 on 2024-12-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0006_tracking_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='callFrequency',
            field=models.IntegerField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
