# Generated by Django 4.2.17 on 2024-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0007_leads_callfrequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='callFrequency',
            field=models.IntegerField(),
        ),
    ]
